23-06-2023

diff --git a/.local/bin/sway-run b/.local/bin/sway-run
--- a/.local/bin/sway-run
+++ b/.local/bin/sway-run
@@ -16,8 +16,8 @@ export QT_QPA_PLATFORM="wayland"
 export QT_AUTO_SCREEN_SCALE_FACTOR=1
 # export QT_WAYLAND_DISABLE_WINDOWDECORATION=1 # Banding issue in qtwebengine
 
-export RADV_PERFTEST=video_decode,nv_ms
-
+export RADV_PERFTEST=video_decode
+export ANV_VIDEO_DECODE=1
 
 # card0 = intel, card1 = amd
 # export WLR_DRM_DEVICES=/dev/dri/card0:/dev/dri/card1
@@ -30,5 +30,21 @@ export RADV_PERFTEST=video_decode,nv_ms
 export WLR_RENDERER=vulkan
 # export VK_INSTANCE_LAYERS=VK_LAYER_KHRONOS_validation
 
-systemd-cat --identifier=sway sway $@
-# sway $@ -d > ~/sway.log 2>&1
+case "$1" in
+debug)
+	~/workspace/sway/build/sway/sway -d >~/sway.log 2>&1
+	;;
+drm-debug)
+	sudo dmesg -C
+	sudo dmesg -w >~/dmesg.log &
+	sway -d > ~/sway.log 2>&1
+	;;
+"")
+    systemd-cat --identifier=sway sway
+	# sway > ~/sway.log 2>&1
+    # sway $@ -d > ~/sway.log 2>&1
+	;;
+*)
+	echo >&2 "Invalid argument: $1"
+	exit 1
+esac
